### ISSUE TITLE
Errors out while using trace bitmap

### ISSUE THREAD

**Issue by MinatoKamikaze** [8day/svg2ssa#2]
Whenever I trace an image in inkscape and use svg2ssa, it gives out an error. When I try the svg from example folder of this repo, it works perfectly so I can only guess that I'm doing something wrong while making the svg. (I'm beginner to Inkscape)

Here's the error:
```python
Traceback (most recent call last):
  File "/home/user/svg2ssa/s2s.py", line 87, in <module>
    s2s_main.S2S(path).convert()
  File "/home/user/svg2ssa/s2s_main.py", line 268, in convert
    atts = element.convert()
  File "/home/user/svg2ssa/s2s_main.py", line 175, in convert
    return {key: att.convert() for key, att in atts.items()}
  File "/home/user/svg2ssa/s2s_main.py", line 175, in <dictcomp>
    return {key: att.convert() for key, att in atts.items()}
  File "/home/user/svg2ssa/s2s_svgatts_path.py", line 360, in convert
    path = [SVGD.processing_method[seg.dtype](self, seg) for seg in path]
  File "/home/user/svg2ssa/s2s_svgatts_path.py", line 360, in <listcomp>
    path = [SVGD.processing_method[seg.dtype](self, seg) for seg in path]
  File "/home/user/svg2ssa/s2s_svgatts_path.py", line 289, in V
    seg.data = [self.last_abs_seg.data[-2], seg.data[0]]
TypeError: 'float' object is not subscriptable
```

Here's the svg in question:
[SVG link]( https://files.catbox.moe/pw8r38.svg)

And here's the image I traced:
![rawTS_mask](https://user-images.githubusercontent.com/87075370/126584716-ce7bf1bb-6664-4f62-ba53-2b490ce73b01.png)

Could you tell me what is going wrong?

**Comment by 8day** [comment]
@MinatoKamikaze Thanks for the repot. Now it's fixed. I'm surprised it lived for so long considering how common those commands are.

Edit: BTW, there's some bug with conversion of paths, but considering how huge, complicated, and hard this is SVG is to analyze in Aegisub, further analysis is not worth it... Edges of converted image are not straight, most likely because of some scaling, discarding of `Z` command needed by SSA and SVG differences, etc.

Edit \#2: Damn, forgot to add that you had small border in that image, which messed things up at that scale (~90% of image looked black).

**Comment by MinatoKamikaze** [comment]
Thank you for the fix. It seems to be working now.

I recently moved from Windows to Linux and found myself unable to use tools like AI2ASS. So things like Gimp and Inkscape are completely foreign to me. So I have no idea how that border came to be. I hope I'll figure it out as I use it more.

Thanks for this tool! I'll post another issue if I find one as I continue using it.

**Comment by nedragrevev** [comment]
@8day Any chance of a standalone .exe build with these fixes. I'm having the same issues on occasion and I'm unsure how to build it from the source.

_Edit: Nevermind. I simply installed Python with the Windows Path Environment Variable checked._
